### PR TITLE
0.5.0

### PR DESCRIPTION
**Pull request by CJ-Wright**

### CODE REVIEW

**Review by ericdill — COMMENTED** [review]
@CJ-Wright it seems to still be building all the various versions of numpy. Did you rerender after getting rid of numpy x.x?

**Comment by CJ-Wright** [comment]
@ericdill ready for more review.

**Comment by ericdill** [comment]
looks fine to me. Thanks @CJ-Wright

**Comment by CJ-Wright** [comment]
Thank you!

**Pull request merged**
