### PR TITLE
Rerender the feedstock with 2.1.1. Skip win py36 builds for now.

### PR DESCRIPTION
**Pull request by ericdill**

### CODE REVIEW

**Comment by ericdill** [comment]
Supercedes #4

**Comment by jakirkham** [comment]
This also adds NumPy 1.12. Is that ok or do you want to skip that too?

**Comment by ericdill** [comment]
Yeah that should be fine. Looks like numpy 1.12 is being used in their test suite: https://ci.appveyor.com/project/ESRF/fabio/build/0.4.125/job/4eeroq29t9uupnne#L31

At least that's true for the master branch :man_shrugging: . @tacaswell @danielballan any reason to prefer to not use numpy 1.12 for fabio 0.4.0?

**Comment by danielballan** [comment]
Not as far as I know. Given you found they are testing on it, I think this can go forward.

**Comment by CJ-Wright** [comment]
Would you mind adding me to maintainers?

**Comment by danielballan** [comment]
@ericdill I'm not a maintainer on this. Are you? Can you add @CJ-Wright?

**Comment by danielballan** [comment]
Oh, I just remembered how this works. @CJ-Wright -- open a PR adding yourself to the list of maintainers in the recipe. Sorry for the noise, all.

**Comment by CJ-Wright** [comment]
@ericdill You might try to re-run the windows build now that conda-build is pinned
see https://github.com/conda/conda-build/issues/1853

**Comment by CJ-Wright** [comment]
Cycling to re-run windows build.

**Comment by ericdill** [comment]
> Cycling to re-run windows build.

FWIW you can go directly to appveyor and restart the build there.

**Comment by CJ-Wright** [comment]
Not with my permissions, or I missed the button :(

**Comment by jakirkham** [comment]
Should have permissions, but you may need logout and login under your conda-forge identity in AppVeyor.

**Comment by jakirkham** [comment]
So actually restarting won't fix it. This needs to be re-rendered with 2.2.1+ to fix the issue.

**Comment by ericdill** [comment]
rebased onto master. rerendered with 2.2.2. 🤞 this is fixed

**Comment by CJ-Wright** [comment]
Everything seems to be in order

**Pull request merged**
